language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
env:
  - NODE_VERSION="0.11"
  - NODE_VERSION="0.10" USERNAME=$USERNAME
before_install:
  - nvm install $NODE_VERSION
  - export USERNAME=$USERNAME
  - export EMAIL=$EMAIL
before_script:
  - npm install
script:
  - npm test
